networks:
  backend:
    driver: bridge

services:
  mysql:
    container_name: mbc_w1-mysql
    image: mysql:oraclelinux9
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: employee_db

  redis:
    container_name: mbc_w1-redis
    image: redis:alpine3.22
    networks:
      - backend
    ports:
      - 6379:6379         

  backend:
    container_name: mbc_w1-backend
    depends_on:
      - mysql
      - redis                 
    image: backend:0.0.3-SNAPSHOT
    networks:
      - backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/employee_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password


      SPRING_CACHE_TYPE: redis
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

    ports:
      - 8080:8080
