networks:
  backend:
    driver: bridge
services:
  mysql:
    image: mysql:oraclelinux9
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: employee_db
  backend:
    depends_on:
      - mysql
    image: backend:0.0.2-SNAPSHOT
    networks:
      - backend
    environment:
      SPRING_DATASOURCE_URL:      jdbc:mysql://mysql:3306/employee_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - 8080:8080