version: "3.8"

services:
  mysql:
    image: mysql:oraclelinux9
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: employee_db

  redis:
    image: redis:alpine3.22
    ports:
      - 6379:6379 
    command: ["redis-server","/etc/redis/redis.conf"]        
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
  backend:
    depends_on:
      - mysql
      - redis                 
    image: backend:0.0.4-SNAPSHOT
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/employee_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password


      SPRING_CACHE_TYPE: redis
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

    ports:
      - 8080:8080
