spring:
  application:
    name: backend

  datasource:
    url: jdbc:mysql://${DB_HOST:mysql}:3306/${DB_NAME:employee_db}?createDatabaseIfNotExist=true
    username: ${DB_USER:root}
    password: ${DB_PASS:password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:database/schema.sql

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
